services:
  node:
    container_name: node
    restart: unless-stopped
    image: node:24.3.0-alpine3.22
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    ports:
      - 5173:5173
      - 8000:8000
    volumes:
      - .:/home/node
    networks:
      - node

networks:
  node:
    name: node
